server:
  port: 8080

spring:
  data:
    mongodb:
      database: ddbb
      host: 127.0.0.1
      port: 27017
cbs:
  imagesPath: file:/D:/images/

ddbb:
  challenge:
    #最多可预约到几天后对战
    afterDays: 2
    #助教是否可以发起挑战
    assistantCoachAllowLaunch: false