server:
  port: 8080

spring:
  application:
    name: com.ddbb
  data:
    mongodb:
      database: ddbb
      host: 127.0.0.1
      port: 27017
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/rmall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
#    username: root
#    #password: 123456
#    password: pingG88gL81Sh!
#    druid:
#      connection-properties:
#      initial-size: 10
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: false
#      # allow:          # 允许所有IP访问，生产环境建议配置白名单
  web:
    resources:
      static-locations: classpath:/static/


cbs:
  imagesPath: file:/D:/ddbb_images/
  imagesUrlContext: ddbb_u_images

ddbb:
  allowSendSms: true
  challenge:
    #最多可预约到几天后对战
    afterDays: 2
    #挑战结束多少秒后，关闭挑战
    closeWhenSecondsAfterEndTime: 86400
    #助教是否可以发起挑战
    assistantCoachAllowLaunch: false
    #默认星期几上班
    defaultWorkDay: 1,2,3,4,5,6,7
    #默认上班时间
    defaultWorkTimeStart: 14
    #默认下班时间
    defaultWorkTimeEnd: 22
